process.env.AWS_ACCOUNT_ID="000000000000"
process.env.AWS_SECRET_ACCESS_KEY="local"
process.env.SFN_MOCK_CONFIG="/home/stepfunctionslocal/MockConfigFile.json"
process.env.AWS_DEFAULT_REGION="local"
process.env.AWS_ACCESS_KEY_ID="local"